server:
  port: 8083
  servlet:
    context-path: /sharding

# 2：mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rose.sharding.entity # 配置 Mapper 对应的 XML 文件路径；
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId

# 3：打印sql语句
logging:
  level:
    com:
      rose:
        sharing:
          mapper: debug

sharding:
  jdbc:
    dataSource:
      names: db-test0,db-test1,db-test2
      # 配置主库
      db-test0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url:
        username:
        password:
      # 配置从库
      db-test1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        url:
        username:
        password:
      config:
        masterslave: # 配置读写分离
          #load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
          name: db1s2
          master-data-source-name: db-test0
          slave-data-source-names: db-test1
      props:
        sql: # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
          show: true